FROM tensorflow/tensorflow:1.5.0-py3

RUN apt-get update && apt-get install -y \
	git \
	curl \	    	
	cmake \
	ffmpeg \
	pkg-config \
	qtbase5-dev \
	libqt5opengl5-dev \
	libassimp-dev \
	libpython3.5-dev \
	libboost-python-dev \
	libtinyxml-dev \
	libgl1-mesa-dev \
    	libgl1-mesa-glx \
    	libglew-dev \
    	libosmesa6-dev \
	libopenmpi-dev && \
	apt-get clean \
    	&& rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

# Install Roboschool
ENV ROBOSCHOOL_PATH=/opt/roboschool
WORKDIR /opt
RUN git clone https://github.com/openai/roboschool.git /opt/roboschool
RUN git clone https://github.com/olegklimov/bullet3 -b roboschool_self_collision \
    	&& mkdir bullet3/build \
    	&& cd    bullet3/build \
    	&& cmake -DBUILD_SHARED_LIBS=ON -DUSE_DOUBLE_PRECISION=1 -DCMAKE_INSTALL_PREFIX:PATH=$ROBOSCHOOL_PATH/roboschool/cpp-household/bullet_local_install -DBUILD_CPU_DEMOS=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF  -DBUILD_UNIT_TESTS=OFF -DBUILD_CLSOCKET=OFF -DBUILD_ENET=OFF -DBUILD_OPENGL3_DEMOS=OFF .. \
    	&& make -j4 \
    	&& make install
RUN pip3 install -e /opt/roboschool


RUN cd / && git clone -b experience-selection https://github.com/tddebruin/baselines-experience-selection.git

WORKDIR /baselines-experience-selection
	
RUN pip3 install .


ENTRYPOINT ["/bin/bash"]


	
	 

